pipeline {
    agent any
    parameters {
        string(name: 'GIT_SSH_PATH', defaultValue: 'https://github.com/tavisca-vshah/WebApi.git', description: 'Value For Git Repo')
        string(name: 'SOLUTION_PATH', defaultValue: 'WebApi/WebApi.sln', description: 'Path to the Solution')
    }
    stages {
        
        stage("checkout git"){
        git '$GIT_REPO'
    }
    stage("build"){
        powershell '''
        dotnet build $($env:SOLUTION_PATH) -p:Configuration=release -v:n
        dotnet test $($env:SOLUTION_PATH)
        dotnet publish $($env:SOLUTION_PATH) -c Release
        compress-archive WebApi/bin/Release/netcoreapp2.1/publish/ artifact.zip -Update
        '''
        }
    
    stage("deploy"){
        powershell '''
        expand-archive ../vikram_webapi_build_deploy/artifact.zip ./ -Force
        dotnet publish/WebApi.dll
        '''
    }
    }
}
